# -*- coding: utf-8 -*-
"""ProjetoIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CRNaOTmptatUFJ3mQFw98I7ku37work
"""

!apt-get update
!apt-get install -y zstd
!curl -fsSL https://ollama.com/install.sh | sh

import threading
import subprocess

# Start Ollama service in background

def run_ollama_serve():
  subprocess.Popen(["ollama", "serve"])

thread = threading.Thread(target=run_ollama_serve)
thread.start()

!ollama pull granite4:350m

!uv pip install ollama

!uv pip install rich

import json
from rich import print
from ollama import chat
model = 'granite4:350m'

import sqlite3
from datetime import datetime

DATABASE_NAME = 'biblioteca.db'

def get_db_connection():
    """Establishes a connection to the SQLite database."""
    conn = sqlite3.connect(DATABASE_NAME)
    conn.row_factory = sqlite3.Row # Allows accessing columns by name
    return conn

def create_table():
    """Creates the products table if it doesn't already exist."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS livros (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            nome TEXT NOT NULL,
            editora TEXT NOT NULL,
            autora TEXT NOT NULL,
            genero TEXT NOT NULL
        )
    ''')
    conn.commit()
    conn.close()
    print("Tabela criada com sucesso!")

create_table()

def create_livro(nome, editora, autora, genero) -> str:
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute('''
            INSERT INTO livros (nome, editora, autora, genero)
            VALUES (?, ?, ?, ?)
        ''', (nome, editora, autora, genero))
        conn.commit()
    except sqlite3.IntegrityError:
        print(f"Erro")
    conn.close()

create_livro('crime e castigo','editora 35','dostoievski','romance')
create_livro('craque neto vs neyma', 'editora 36', 'emrao', 'curiosidade')
create_livro('menor', 'editora 35', 'teste', 'teste')

def todos_livros() -> str:
    """
    busque por todos os livros
    """

    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM livros")
    livros = cursor.fetchall()
    conn.close()
    return '\n'.join([', '.join(map(str, row)) for row in livros])

todos_livros()

def buscar_por_nome(nome) -> str:
    """
    Lista todos os livros na ordem natural do banco de dados (por ID).
    NÃO USE esta função se o usuário pedir qualquer tipo de ordenação ou filtro por tamanho.
    """

    conn = get_db_connection()
    cursor = conn.cursor()

    query = "SELECT * FROM livros WHERE nome LIKE ?"
    cursor.execute(query, ('%' + nome + '%',))

    livros = cursor.fetchall()
    conn.close()

    if not livros:
        return "Nenhum livro encontrado."

    resultado = []
    for livro in livros:
        id_, nome_livro, editora, autora, genero = livro
        resultado.append(f"ID: {id_} Nome: {nome_livro} Editora: {editora} Autora: {autora} Gênero: {genero}")

    return (resultado)

buscar_por_nome('crime e castigo')

def ordenar_por_tamanho_nome() -> str:
    """
    ESTA É A ÚNICA FUNÇÃO QUE ORDENA. Use exclusivamente para pedidos de
    organizar por TAMANHO, COMPRIMENTO ou QUANTIDADE DE CARACTERES do nome.
    """

    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM livros")
    livros = cursor.fetchall()
    conn.close()

    if not livros:
        return "Nenhum livro encontrado no banco de dados."

    # Ordena pelo tamanho da string no índice 1 (nome).
    livros_ordenados = sorted(livros, key=lambda x: len(str(x[1] or "")))

    resultado = []
    for livro in livros_ordenados:
        id_, nome_livro, editora, autora, genero = livro
        resultado.append(f"ID: {id_} | Nome: {nome_livro} | Autora: {autora}")

    return '\n'.join(resultado)

# --- Fluxo de Chat Corrigido ---

messages = [{'role': 'user', 'content': 'ordene todos os livros por tamanho do nome'}]
print('Prompt:', messages[0]['content'])

# Chamada do modelo
response = chat(model, messages=messages, tools=[buscar_por_nome, todos_livros, ordenar_por_tamanho_nome])

if response.message.tool_calls:
    tool = response.message.tool_calls[0]
    nome_funcao = tool.function.name
    argumentos = tool.function.arguments

    print(f'Função chamada: {nome_funcao}({argumentos})')

    if nome_funcao in locals():
        funcao_para_chamar = locals()[nome_funcao]

        # Resolve o erro de TypeError:
        # Tenta chamar com argumentos; se falhar porque a IA inventou argumentos vazios, chama sem nada.
        try:
            if argumentos:
                result = funcao_para_chamar(**argumentos)
            else:
                result = funcao_para_chamar()
        except TypeError:
            result = funcao_para_chamar()

        print(f'--- Resultado ---\n{result}')
    else:
        print(f"Erro: Função {nome_funcao} não encontrada.")
else:
    print('Resposta da IA:', response.message.content)



messages = [{'role': 'user', 'content': 'busque o livro com nome crime e castigo'}]
print('Prompt:', messages[0]['content'])

response = chat(model, messages=messages, tools=[buscar_por_nome, todos_livros])
###print(response.message.tool_calls) ### na segunda vez ele fica none - nulo
if response.message.tool_calls:
  tool = response.message.tool_calls[0]
  print(f'Funcao chamada: {tool.function.name}({tool.function.arguments})')

  result = locals()[tool.function.name](**tool.function.arguments) ### chamando uma func() usando seu nome em string
  print(f'Result: {result}')

  ###messages.append(response.message)
  ###messages.append({'role': 'tool', 'content': result})

  ###print('Messages:', messages)

  ###final = chat(model, messages=messages) ### isso eh uma grande instabilidade - usar o LM para gerar a resposta
  ###print('Response:', final.message.content)
else:
  print('Response:', response.message.content)